apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-springboot
  template:
    metadata:
      labels:
        app: demo-springboot
    spec:
      containers:
        - name: demo-springboot
          image: demo-springboot:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
